### ISSUE TITLE
Question: Should index=false on import dataframe?

### ISSUE THREAD

**Issue by joehand** [karissa/datpy#8]
Right now when you import a dataframe you get the index column inside of dat (first row, w/ blank key):

```
 {'': '769',
  'agency': 'POLICE',
  'amtRemaining': '$13698.13',}
```
This is because `dataframe.to_csv()` ([here](https://github.com/karissa/datpy/blob/master/datpy.py#L106)) exports with the index. 

It seems like this behavior is unexpected, unless the index has been purposefully set. Making it `dataframe.to_csv(index=False)` will remove the index but maybe this should be an argument in import_dataframe?

**Comment by karissa** [comment]
Yeah, I think you're right -- maybe index=False should be defaulted to False, but be able to be set the other way. I don't think dat guarantees order on export. 

The index could also be used as the identifying key, by default, unless otherwise specified. What do you think?

I'm going to add you as a collaborator on the repo so we can work on the same branches. Feel free to open PRs and experiment

**Comment by joehand** [comment]
> The index could also be used as the identifying key, by default, unless otherwise specified. What do you think?

`dat import` will overwrite the row if the key is the same, right? If that is the case, then setting key to the index by default may be troublesome. If we have two separate cities dataframes and import both of them into the same dataset, the indexes will overlap.

But if the index has been [purposefully set](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.set_index.html), then we don't want to throw that out (and it should probably be used as the key). I wonder if you can tell if the index has been set to something besides default.

I'll open a branch so we can start working through it.
